"""4e — mutation catch rate: how much broken code does this grader actually catch?

The sibling of `audit.honest`, and deliberately the same shape:

    honest_pass = accepted / |{s : oracle(s) = 1}|      of CORRECT solutions, how many accepted
    catch_rate  = rejected / |{m : oracle(m) = 0}|      of BROKEN mutants,   how many rejected

Together they are the grader's sensitivity and specificity against the oracle, and they are the
two columns of the report. A grader can trivially max either one alone — accept everything, or
reject everything — so neither number means anything without the other next to it.

Why mutants rather than red-agent runs: they are generated by AST surgery on the reference, so
they are deterministic, reproducible, and cost nothing in API spend. That makes the "how strong
is this grader" column affordable on a $150 budget (TestBench-Forge used the same trick at the
hackathon: an AST mutation engine plus a differential filter keeping only catchable bugs).

The differential filter is the load-bearing part. A mutant the ORACLE still accepts is
behaviourally equivalent on the oracle's inputs — it is not a bug, so a grader that accepts it
has done nothing wrong. Equivalent mutants are the classic confound of mutation testing; they
are filtered out and counted, never scored.
"""

from __future__ import annotations

import ast
from collections.abc import Callable, Iterable
from dataclasses import dataclass

from ..grader import Grader

# Single-point operator swaps. Small and boring on purpose: every mutant must be a plausible
# off-by-one or inverted-condition bug, not a syntactic curiosity.
_CMP_SWAPS = {
    ast.Lt: ast.LtE,
    ast.LtE: ast.Lt,
    ast.Gt: ast.GtE,
    ast.GtE: ast.Gt,
    ast.Eq: ast.NotEq,
    ast.NotEq: ast.Eq,
    ast.In: ast.NotIn,
    ast.NotIn: ast.In,
}
_BIN_SWAPS = {
    ast.Add: ast.Sub,
    ast.Sub: ast.Add,
    ast.Mult: ast.FloorDiv,
    ast.FloorDiv: ast.Mult,
}
_BOOL_SWAPS = {ast.And: ast.Or, ast.Or: ast.And}


@dataclass(frozen=True)
class Mutant:
    """One single-point mutation of the reference. `label` locates it, for the repro."""

    label: str
    source: str


@dataclass(frozen=True)
class MutationReport:
    task_id: str
    generated: int
    equivalent: tuple[str, ...] = ()  # oracle accepted them — not bugs, excluded from the rate
    caught: int = 0
    escaped: tuple[Mutant, ...] = ()  # real bugs this grader cannot see: the useful artifact
    grader_patches: tuple[str, ...] = ()

    @property
    def catchable(self) -> int:
        """The population: mutants the oracle confirmed are genuinely broken."""
        return self.caught + len(self.escaped)

    @property
    def catch_rate(self) -> float | None:
        return self.caught / self.catchable if self.catchable else None

    @property
    def population(self) -> str:
        return (
            f"catch_rate = rejected / |{{m in {self.generated} mutants : oracle(m) = 0}}| "
            f"= {self.caught}/{self.catchable}"
        )


class _Mutator(ast.NodeTransformer):
    """Applies exactly the `target`-th mutation site and leaves every other site alone."""

    def __init__(self, target: int):
        self.target = target
        self.seen = 0
        self.label = ""

    def _hit(self, name: str, node) -> bool:
        match = self.seen == self.target
        if match:
            self.label = f"{name}@L{getattr(node, 'lineno', 0)}"
        self.seen += 1
        return match

    def visit_Compare(self, node):
        self.generic_visit(node)
        for i, op in enumerate(node.ops):
            swap = _CMP_SWAPS.get(type(op))
            if swap and self._hit(f"cmp:{type(op).__name__}->{swap.__name__}", node):
                node.ops[i] = swap()
        return node

    def visit_BinOp(self, node):
        self.generic_visit(node)
        swap = _BIN_SWAPS.get(type(node.op))
        if swap and self._hit(f"bin:{type(node.op).__name__}->{swap.__name__}", node):
            node.op = swap()
        return node

    def visit_BoolOp(self, node):
        self.generic_visit(node)
        swap = _BOOL_SWAPS.get(type(node.op))
        if swap and self._hit(f"bool:{type(node.op).__name__}->{swap.__name__}", node):
            node.op = swap()
        return node

    def visit_Constant(self, node):
        if isinstance(node.value, bool):
            if self._hit(f"const:{node.value}->{not node.value}", node):
                return ast.copy_location(ast.Constant(value=not node.value), node)
        elif isinstance(node.value, int) and self._hit(
            f"const:{node.value}->{node.value + 1}", node
        ):
            return ast.copy_location(ast.Constant(value=node.value + 1), node)
        return node


def _site_count(source: str) -> int:
    probe = _Mutator(target=-1)
    probe.visit(ast.parse(source))
    return probe.seen


def generate_mutants(source: str, limit: int | None = None) -> list[Mutant]:
    """Every single-point mutant of `source`, in deterministic order.

    One mutation per mutant, so an escape localizes to exactly one operator. `limit` truncates
    from the front; the order is stable across runs, so a capped run is reproducible.
    """
    total = _site_count(source)
    mutants: list[Mutant] = []
    for i in range(total if limit is None else min(total, limit)):
        mutator = _Mutator(target=i)
        tree = mutator.visit(ast.parse(source))
        ast.fix_missing_locations(tree)
        mutated = ast.unparse(tree)
        if mutated != source and mutator.label:
            mutants.append(Mutant(label=mutator.label, source=mutated))
    return mutants


def measure_catch_rate(
    grader: Grader,
    mutants: Iterable[Mutant],
    *,
    grade: Callable[[Grader, str], int],
    verify: Callable[[Grader, str], int],
) -> MutationReport:
    """Filter mutants to the genuinely broken, then ask what fraction the grader rejects."""
    generated = 0
    caught = 0
    equivalent: list[str] = []
    escaped: list[Mutant] = []

    for mutant in mutants:
        generated += 1
        if verify(grader, mutant.source) == 1:
            equivalent.append(mutant.label)  # oracle says it still behaves; not a bug
            continue
        if grade(grader, mutant.source) == 0:
            caught += 1
        else:
            escaped.append(mutant)

    return MutationReport(
        task_id=grader.task.task_id,
        generated=generated,
        equivalent=tuple(equivalent),
        caught=caught,
        escaped=tuple(escaped),
        grader_patches=tuple(grader.patches),
    )
